FROM nvcr.io/nvidia/tensorflow:21.05-tf1-py3
RUN set -x \
&& apt update \
&& apt install -y libsm6 libxext6 libxrender-dev \
&& pip install --no-cache-dir absl-py==0.9.0 \
&& pip install --no-cache-dir argon2-cffi==20.1.0 \
&& pip install --no-cache-dir asn1crypto==0.24.0 \
&& pip install --no-cache-dir astor==0.8.1 \
&& pip install --no-cache-dir astunparse==1.6.3 \
&& pip install --no-cache-dir async-generator==1.10 \
&& pip install --no-cache-dir attrs==20.3.0 \
&& pip install --no-cache-dir audioread==2.1.9 \
&& pip install --no-cache-dir backcall==0.2.0 \
&& pip install --no-cache-dir bleach==3.3.0 \
&& pip install --no-cache-dir certifi==2020.12.5 \
&& pip install --no-cache-dir cffi==1.14.5 \
&& pip install --no-cache-dir chardet==4.0.0 \
&& pip install --no-cache-dir click==7.1.2 \
&& pip install --no-cache-dir cloudpickle==1.6.0 \
&& pip install --no-cache-dir contextlib2==0.6.0.post1 \
&& pip install --no-cache-dir cupy-cuda112==9.0.0 \
&& pip install --no-cache-dir cycler==0.10.0 \
&& pip install --no-cache-dir Cython==0.29.23 \
&& pip install --no-cache-dir decorator==4.4.2 \
&& pip install --no-cache-dir defusedxml==0.7.1 \
&& pip install --no-cache-dir DLLogger==0.1.0 \
&& pip install --no-cache-dir entrypoints==0.3 \
&& pip install --no-cache-dir fastrlock==0.6 \
&& pip install --no-cache-dir Flask==1.1.2 \
&& pip install --no-cache-dir flatbuffers==1.12 \
&& pip install --no-cache-dir future==0.18.2 \
&& pip install --no-cache-dir gast==0.3.3 \
&& pip install --no-cache-dir google-pasta==0.2.0 \
&& pip install --no-cache-dir googledrivedownloader==0.4 \
&& pip install --no-cache-dir graphsurgeon==0.4.5 \
&& pip install --no-cache-dir grpcio==1.37.0 \
&& pip install --no-cache-dir h5py==2.10.0 \ 
&& pip install --no-cache-dir horovod==0.21.3 \
&& pip install --no-cache-dir html2text==2020.1.16 \
&& pip install --no-cache-dir idna==2.10 \
&& pip install --no-cache-dir iniconfig==1.1.1 \
&& pip install --no-cache-dir ipykernel==5.5.3 \
&& pip install --no-cache-dir ipython==7.22.0 \
&& pip install --no-cache-dir ipython-genutils==0.2.0 \
&& pip install --no-cache-dir itsdangerous==1.1.0 \
&& pip install --no-cache-dir jedi==0.18.0 \
&& pip install --no-cache-dir Jinja2==2.11.3 \
&& pip install --no-cache-dir joblib==0.17.0 \
&& pip install --no-cache-dir json5==0.9.5 \
&& pip install --no-cache-dir jsonschema==3.2.0 \
&& pip install --no-cache-dir jupyter-client==6.1.12 \
&& pip install --no-cache-dir jupyter-core==4.7.1 \
&& pip install --no-cache-dir jupyter-tensorboard==0.2.0 \
&& pip install --no-cache-dir jupyterlab==2.3.1 \
&& pip install --no-cache-dir jupyterlab-pygments==0.1.2 \
&& pip install --no-cache-dir jupyterlab-server==1.2.0 \
&& pip install --no-cache-dir jupytext==1.11.1 \
&& pip install --no-cache-dir Keras==2.1.2 \
&& pip install --no-cache-dir Keras-Applications==1.0.8 \
&& pip install --no-cache-dir Keras-Preprocessing==1.1.0 \
&& pip install --no-cache-dir kiwisolver==1.3.1 \
&& pip install --no-cache-dir librosa==0.7.1 \
&& pip install --no-cache-dir llvmlite==0.32.1 \
&& pip install --no-cache-dir Markdown==3.3.4 \
&& pip install --no-cache-dir markdown-it-py==0.6.2 \
&& pip install --no-cache-dir MarkupSafe==1.1.1 \
&& pip install --no-cache-dir matplotlib==3.3.2 \
&& pip install --no-cache-dir mdit-py-plugins==0.2.6 \
&& pip install --no-cache-dir mistune==0.8.4 \
&& pip install --no-cache-dir mock==3.0.5 \
&& pip install --no-cache-dir mpi4py==3.0.3 \
&& pip install --no-cache-dir munch==2.5.0 \
&& pip install --no-cache-dir nbclient==0.5.3 \
&& pip install --no-cache-dir nbconvert==6.0.7 \
&& pip install --no-cache-dir nbformat==5.1.3 \
&& pip install --no-cache-dir nest-asyncio==1.5.1 \
&& pip install --no-cache-dir networkx==2.5.1 \
&& pip install --no-cache-dir nibabel==3.2.1 \
&& pip install --no-cache-dir nltk==3.4.5 \
&& pip install --no-cache-dir notebook==6.2.0 \
&& pip install --no-cache-dir numba==0.46.0 \
&& pip install --no-cache-dir numpy==1.17.3 \
&& pip install --no-cache-dir nvidia-dali-cuda110==1.0.0 \
&& pip install --no-cache-dir nvidia-dali-tf-plugin-cuda110==1.0.0 \
&& pip install --no-cache-dir nvidia-tensorboard==1.15.0+nv21.4 \
&& pip install --no-cache-dir nvidia-tensorboard-plugin-dlprof==1.2.0 \
&& pip install --no-cache-dir nvtx-plugins==0.1.8 \
&& pip install --no-cache-dir onnx==1.9.0 \
&& pip install --no-cache-dir opencv-python==4.2.0.34 \
&& pip install --no-cache-dir opt-einsum==3.3.0 \
&& pip install --no-cache-dir packaging==20.9 \
&& pip install --no-cache-dir pandas==0.25.3 \
&& pip install --no-cache-dir pandocfilters==1.4.3 \
&& pip install --no-cache-dir parso==0.8.2 \
&& pip install --no-cache-dir pexpect==4.7.0 \
&& pip install --no-cache-dir pickleshare==0.7.5 \
&& pip install --no-cache-dir Pillow==8.1.2 \
&& pip install --no-cache-dir pip==21.1 \
&& pip install --no-cache-dir pluggy==0.13.1 \
&& pip install --no-cache-dir polygraphy==0.29.0 \
&& pip install --no-cache-dir portalocker==2.3.0 \
&& pip install --no-cache-dir portpicker==1.3.1 \
&& pip install --no-cache-dir progressbar==2.5 \
&& pip install --no-cache-dir prometheus-client==0.10.1 \
&& pip install --no-cache-dir prompt-toolkit==3.0.18 \
&& pip install --no-cache-dir protobuf==3.15.8 \
&& pip install --no-cache-dir psutil==5.7.0 \
&& pip install --no-cache-dir ptyprocess==0.7.0 \
&& pip install --no-cache-dir py==1.10.0 \
&& pip install --no-cache-dir pycocotools==2.0.0 \
&& pip install --no-cache-dir pycparser==2.20 \
&& pip install --no-cache-dir Pygments==2.8.1 \
&& pip install --no-cache-dir pyparsing==2.4.7 \
&& pip install --no-cache-dir pyrsistent==0.17.3 \
&& pip install --no-cache-dir pytest==6.2.3 \
&& pip install --no-cache-dir python-dateutil==2.8.1 \
&& pip install --no-cache-dir python-speech-features==0.6 \
&& pip install --no-cache-dir pytz==2021.1 \
&& pip install --no-cache-dir PyYAML==5.4.1 \
&& pip install --no-cache-dir pyzmq==22.0.3 \
&& pip install --no-cache-dir requests==2.25.1 \
&& pip install --no-cache-dir resampy==0.2.2 \
&& pip install --no-cache-dir sacrebleu==1.2.10 \
&& pip install --no-cache-dir scikit-learn==0.24.2 \
&& pip install --no-cache-dir scipy==1.4.1 \
&& pip install --no-cache-dir Send2Trash==1.5.0 \
&& pip install --no-cache-dir sentencepiece==0.1.94 \
&& pip install --no-cache-dir setuptools==56.0.0 \
&& pip install --no-cache-dir SimpleITK==2.0.1 \
&& pip install --no-cache-dir six==1.13.0 \
&& pip install --no-cache-dir SoundFile==0.10.3.post1 \
&& pip install --no-cache-dir tensorrt==7.2.3.4 \
&& pip install --no-cache-dir termcolor==1.1.0 \
&& pip install --no-cache-dir terminado==0.9.4 \
&& pip install --no-cache-dir testpath==0.4.4 \
&& pip install --no-cache-dir tf2onnx==1.8.4 \
&& pip install --no-cache-dir threadpoolctl==2.1.0 \
&& pip install --no-cache-dir toml==0.10.2 \
&& pip install --no-cache-dir toposort==1.6 \
&& pip install --no-cache-dir torch==1.6.0 \
&& pip install --no-cache-dir torchvision==0.7.0 \
&& pip install --no-cache-dir tornado==6.1 \
&& pip install --no-cache-dir tqdm==4.60.0 \
&& pip install --no-cache-dir traitlets==5.0.5 \
&& pip install --no-cache-dir typing==3.7.4.3 \
&& pip install --no-cache-dir typing-extensions==3.7.4.3 \
&& pip install --no-cache-dir uff==0.6.9 \
&& pip install --no-cache-dir urllib3==1.26.4 \
&& pip install --no-cache-dir wcwidth==0.2.5 \
&& pip install --no-cache-dir webencodings==0.5.1 \
&& pip install --no-cache-dir Werkzeug==1.0.1 \
&& pip install --no-cache-dir wheel==0.36.2 \
&& pip install --no-cache-dir wrapt==1.12.1 \
&& pip install --no-cache-dir skimage==0.18.0

WORKDIR  /home/ubuntu:/home/ubuntu
COPY new.sh /home/ubuntu/

CMD bash /home/ubuntu/new.sh
